model: "MACE"

# foundation_model is selected by train_wB.sh from experiment_wA/checkpoints_<split_seed>/mace_run-<member_seed>.model.
multiheads_finetuning: False

name: "mace"
model_dir: "experiment_wB/models_0"
log_dir: "experiment_wB/logs_0"
checkpoints_dir: "experiment_wB/checkpoints_0"
results_dir: "experiment_wB/results_0"

train_file: "dataset/water_0/ccsdt/train.xyz"
valid_file: "dataset/water_0/ccsdt/val.xyz"
test_file: "dataset/water_0/ccsdt/test.xyz"
energy_key: "REF_energy"
# forces_key: "REF_forces"

lr: 0.0005
num_channels: 128
max_L: 1
r_max: 6.0
forces_weight: 0.0
device: cuda
batch_size: 8
max_num_epochs: 100
swa: False
compute_forces: False
E0s: "average"
predict_mve: True
loss: "gaussian_nll"
eval_interval: 1
save_all_checkpoints: True
log_epoch_outputs: False
default_dtype: "float32"
enable_cueq: False

wandb: True
wandb_dir: "wandb"
wandb_entity: "uq-mf"
wandb_project: "experiment_wB"
