
model: "MACE"
num_channels: 128
max_L: 2
r_max: 6.0
name: "mace-default"
model_dir: "outputs/models"
log_dir: "outputs/logs"
checkpoints_dir: "outputs/checkpoints"
results_dir: "outputs/results"
train_file: "dataset/ani1x-processed/test.xyz"
valid_file: "dataset/ani1x-processed/val.xyz"
test_file: "dataset/ani1x-processed/test.xyz"
energy_key: "wb97x_dz.energy"
# forces_key: "wb97x_dz.forces"
forces_weight: 0.0
device: cuda
batch_size: 20
max_num_epochs: 1000
swa: False
compute_forces: False
E0s: "average"
seed: 0
predict_mve: False
loss: "energy_only"
patience: 100
# enable_cueq: True

