
model: "MACE"
num_channels: 64
max_L: 1
r_max: 5.0
name: "mace-mv-sp"
model_dir: "outputs/models"
log_dir: "outputs/logs"
checkpoints_dir: "outputs/checkpoints"
results_dir: "outputs/results"
train_file: "dataset/ani1x-processed/train.xyz"
valid_file: "dataset/ani1x-processed/val.xyz"
test_file: "dataset/ani1x-processed/test.xyz"
energy_key: "wb97x_dz.energy"
forces_weight: 0.0
device: cuda
batch_size: 100
max_num_epochs: 200
swa: False
compute_forces: False
E0s: "average"
predict_mve: True
loss: "gaussian_nll"
# patience: 20
eval_interval: 1
save_all_checkpoints: False
log_epoch_outputs: True

