
model: "MACE"
num_channels: 128
max_L: 0
r_max: 5.0
name: "mace01"
model_dir: "MACE_models"
log_dir: "MACE_models_logs"
checkpoints_dir: "MACE_models_checkpoints"
results_dir: "MACE_models_results"
train_file: "test_data/solvent_xtb_train_200.xyz"
valid_fraction: 0.10
test_file: "test_data/solvent_xtb_test.xyz"
energy_key: "energy_xtb"
forces_key: "forces_xtb"
device: cuda
batch_size: 10
max_num_epochs: 10
swa: True
seed: 123
predict_mve: True
loss: "gaussian_nll"
